### ISSUE TITLE
Solve challenge in C++

### ISSUE THREAD

**Issue by s-bridges** [s-bridges/Hacktoberfest_Fizzbuzz#1]

**Comment by acebby** [comment]
I'll take this up. I assume whitespace characters aren't counted?

**Comment by Davidgokimmung** [comment]
I'd like to take this up.

**Comment by s-bridges** [comment]
You all are more than welcome to tackle it. There are a ton of different ways to do it so feel free and in any language too, I was just getting the ball rolling!
